[project]
name = "fedex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.1.0",
    "pdf2image>=1.17.0",
    "pypdf>=6.1.1",
]
